set(ExternLibraries)
foreach(BoardSize RANGE 1 ${MaxBoardSize})
  add_subdirectory(core "source/core/core${BoardSize}x${BoardSize}")
  add_subdirectory(frontend "source/frontend/frontend${BoardSize}x${BoardSize}")
  add_subdirectory(extern "source/extern/extern${BoardSize}x${BoardSize}")
  list(APPEND ExternLibraries ${ExternLibraryName})
endforeach()

add_subdirectory(cmd "source/cmd")
qt_add_executable("${PROJECT_NAME}" main.cpp)
target_compile_definitions("${PROJECT_NAME}" PRIVATE __MaxBoardSize__=${MaxBoardSize})
target_link_libraries("${PROJECT_NAME}" PRIVATE ${CommandLibraryName})