set(ExternLibraries)
foreach(BoardSize RANGE 1 ${MaxBoardSize})
  add_subdirectory(model "model/model@${BoardSize}x${BoardSize}")
  add_subdirectory(board "board/board@${BoardSize}x${BoardSize}")
  add_subdirectory(robot "robot/robot@${BoardSize}x${BoardSize}")
  add_subdirectory(frontend "frontend/frontend@${BoardSize}x${BoardSize}")
  add_subdirectory(extern "extern/extern@${BoardSize}x${BoardSize}")
  list(APPEND ExternLibraries ${ExternLibraryName})
endforeach()
add_subdirectory(command)
qt_add_executable("${PROJECT_NAME}" main.cpp)
target_link_libraries("${PROJECT_NAME}" PRIVATE ${CommandLibraryName})