name: macOS Build

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install requirements
        run: |
          brew install coreutils qt@6 tbb
          echo "CMAKE_PREFIX_PATH=$(brew --prefix qt@6)/lib/cmake" >> $GITHUB_ENV

      - name: Configure CMake
        run: |
          cmake -B build -S . -DCMAKE_PREFIX_PATH=$(brew --prefix qt@6)/lib/cmake

      - name: Build
        run: |
          cmake --build build -j $(nproc)
