name: macOS Build

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install requirements
        run: |
          brew update
          brew install coreutils qt@6 tbb llvm

      - name: Build
        run: |
          cmake -B build -S .
          cmake --build build -j $(nproc)

      - name: Run
        run: |
          ./build/Dots_and_Boxes -s 5 -b
